import { useState, useEffect } from "react";
import { onAuthStateChanged } from "firebase/auth";
import Head from "next/head";
import ChatArea from "../components/ChatArea";
import Header from "../components/Header";
import Register from "../components/Register";
import Sidebar from "../components/Sidebar";
import { auth, db } from "../firebase";
import { where, query, collection, getDocs } from "firebase/firestore";

export default function Home() {
  const [userID, setUserID] = useState(null);
  const [userData, setUserData] = useState(null);

  onAuthStateChanged(auth, (user) => {
    if (user) {
      setUserID(user?.uid);
    }
  });

  const getUserData = async () => {
    const userRef = collection(db, "users");
    const q = query(userRef, where("uid", "==", `${auth?.currentUser?.uid}`));
    const querySnapshot = await getDocs(q);
    querySnapshot.docs.forEach((doc) => {
      if (doc.exists()) {
        setUserData(doc.data());
        
      }
    });
  };

  useEffect(() => {
    getUserData();
  }, [userID]);

  return !userID ? (
    <Register />
  ) : (
    <div className="h-screen">
      <Head>
        <title>Chat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header
        displayPhoto={userData?.displayPhoto}
        displayName={userData?.displayName}
        
      />

      <main className="grid grid-cols-4">
        <Sidebar displayName={userData?.displayName}/>
        <ChatArea displayName={userData?.displayName}/>
      </main>
    </div>
  );
}
